Fix signal handling in DocViewWindow
close signal was incorrectly connected to closeEvent method which
generated debug tracebacks

ERROR sas.qtgui.Perspectives.Fitting.FittingWidget (FittingWidget.py:148) :: TypeError: DocViewWindow.closeEvent() missing 1 required positional argument: 'event'